config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'home', to: 'pages#home'
  get 'projects', to: 'pages#projects'
  get 'contact', to: 'pages#contact'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portafolio</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Portafolio</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Home', home_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Projects', projects_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Contact', contact_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/pages/contact.html.erb
<h1>Contacto</h1>
<ul>
    <li><%= image_tag 'git.png', class: 'iconogit' %> <a href="https://github.com/xDani-R" target="_blank">GitHub</a></li>
    <br>
    <li><%= image_tag 'ins.png', class: 'icono' %> <a href="https://www.instagram.com/dx_xniel_?igsh=aDc4cmlibjQyMGxi" target="_blank">Instagram</a></li>
</ul>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>Bienvenido a mi portafolio</p>
<div class="card mb-3" style="max-width: 100%;">
    <div class="row g-0">
    <div class="col-md-4">
        <%= image_tag 'foto_perfil', class: 'profile_img' %>
    </div>
    <div class="col-md-8">
        <div class="card-body">
        <h5 class="card-title">Perfil</h5>
        <ul>
            <li>Nombre: Cesar Daniel</li>
        </ul>
        <ul>
            <li>Apellido: Caceres Rodriguez</li>
        </ul>
        <ul>
            <li>Descripcion</li>
            <p>Aqui comenzando un nuevo camino en la programación conociendo diferentes tipos de lenguaje como Python, HTML, CSS y JavaScript. Ahora dando los primeros pasos en ocupar Ruby on Rails.</p>
        </ul>
        </div>
    </div>
    </div>
</div>

app/views/pages/projects.html.erb
<h1>Projects</h1>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <%= image_tag 'CV', class: 'proyect1' %>
        <div class="card-body">
          <h5 class="card-title">Mi Curriculum</h5>
          <a href="#" class="btn btn-primary ver-mas">Ver más</a>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <%= image_tag 'IGUANA', class: 'proyect2' %>
        <div class="card-body">
          <h5 class="card-title">Iguana</h5>
          <a href="#" class="btn btn-primary ver-mas">Ver más</a>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <%= image_tag 'SURICATA', class: 'proyect3' %>
        <div class="card-body">
          <h5 class="card-title">Suricata</h5>
          <a href="#" class="btn btn-primary ver-mas">Ver más</a>
        </div>
      </div>
    </div>
  </div>
</div>